# Generated by Django 3.1.6 on 2023-05-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_chaussures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille_pied', models.IntegerField()),
                ('genre', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='user_pantalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourTaille', models.IntegerField()),
                ('tourHanche', models.IntegerField()),
                ('genre', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='user_tee_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.IntegerField()),
                ('poids', models.IntegerField()),
                ('genre', models.CharField(max_length=1)),
            ],
        ),
    ]
