# Generated by Django 3.1.6 on 2023-05-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_chaussures',
            name='taille_pied',
            field=models.FloatField(),
        ),
    ]
